export interface Admin {
  id?: number; // Optional as it may be generated by the database
  firstName: string; // First name of the admin
  lastName: string; // Last name of the admin
  email: string; // Email address for authentication and contact
  password?: string; // Password for authentication purposes (optional when fetching data)
  position?: string; // Admin position
  phoneNumber?: string; // Phone number for contact
  role?: string; // Role (e.g., ADMIN)
}
export interface AuthenticationRequest {
  email: string;
  password: string;
}
export interface AuthenticationResponse {
  token: string;
  jwt: string;
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  position: string;
  phoneNumber?: string;
}
