export interface Location {
  id?: number; // Optional, as it may be generated by the database
  name: string; // Name of the location
  type: string; // Type of the location, e.g., Building, Facility
  latitude: number; // Latitude coordinate
  longitude: number; // Longitude coordinate
  description?: string; // Optional description of the location
  area: string; // Area where the location belongs
}
