export interface MapInteraction {
  id?: number; // Optional as it may be generated by the database
  panelId: number; // ID reference to the panel that recorded the interaction
  interactionType: string; // Type of interaction (e.g., click, zoom, etc.)
  timestamp: Date; // Date and time when the interaction occurred
}
