export interface Panel {
  id?: number; // Optional as it may be generated by the database
  ipAddress: string; // IP address of the panel
  locationId: number;
  latitude: number;
  longitude: number;
  buildingName: string;
  status: string;// ID reference to the location of the panel
}
