export interface Route {
  id?: number; // Optional as it may be generated by the database
  startLatitude: number; // Latitude coordinate for the starting point of the route
  startLongitude: number; // Longitude coordinate for the starting point of the route
  endLatitude: number; // Latitude coordinate for the ending point of the route
  endLongitude: number; // Longitude coordinate for the ending point of the route
  distance?: number; // Distance of the route (optional, may be calculated)
  estimatedTime?: number; // Estimated travel time (optional, may be calculated)
}
